server:
  port: 8080

spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    suffix: .html

#DB configuration
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - mapper/*.xml
  type-aliases-package: com.heeseong.security.model

--- #local
spring:
  profiles: local
  datasource:
    hikari:
      pool-name: hikari-cp
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&verifyServerCertificate=false&useSSL=false
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: root
      password: 1234

logging:
  level:
    org.springframework.web: info
    com.heeseong: info
    jdbc.sqlonly : off
    jdbc.sqltiming : off
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable : off
    jdbc.connection: off
file:
  path: D:${file.separator}log${file.separator}

default-upload-path: D:${file.separator}upload${file.separator}

--- #dev

--- #prod